server:
  port: 8096



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootclass?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bootuser
    password: 1234
  thymeleaf:
    cache: false

  # JPA 관련 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


      mail:
        host: smtp.gmail.com
        port: 587
        username: "rlaxodhks36@naver.com"
        password: "xodhks7196@"
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true

                spring.thymeleaf.prefix=classpath:templates/
                spring.thymeleaf.check-template-location=true
                spring.thymeleaf.suffix=.html
                spring.thymeleaf.mode=HTML5
                spring.thymeleaf.cache=false
                spring.thymeleaf.order=0
